alter database stylish character set utf8;
alter table product character set utf8;
alter table color character set utf8;
alter table hots character set utf8;
alter table hots_title character set utf8;
alter table product_images character set utf8;
alter table stock character set utf8;
alter table users character set utf8;
alter table campaign character set utf8;
alter table product change title title char(50) character set utf8;
alter table product change description description char(50) character set utf8;
alter table product change texture texture char(50) character set utf8;
alter table product change wash wash char(50) character set utf8;
alter table product change place place char(50) character set utf8;
alter table product change note note char(50) character set utf8;
alter table product change story story char(50) character set utf8;
alter table product change category category char(50) character set utf8;
alter table product change main_image main_image char(50) character set utf8;
alter table campaign change story story char(50) character set utf8;
alter table campaign change image image char(50) character set utf8;
alter table color change code code char(50) character set utf8;
alter table color change name name char(50) character set utf8;
alter table hots change title title char(50) character set utf8;
alter table hots_title change title title char(50) character set utf8;
alter table product_images change image image char(50) character set utf8;
alter table stock change color_code color_code char(50) character set utf8;
alter table stock change size size char(50) character set utf8;
alter table users change name name char(50) character set utf8;
alter table users change email email char(50) character set utf8;
alter table users change picture picture char(50) character set utf8;
